name: sfmc_flutter
description: Salesforce Marketing Cloud implementation for Flutter for both iOS and Android. Integrate SF Marketing Cloud (SFMC 7.x.x)
version: 1.0.2
homepage: https://www.dribba.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.dribba.sfmc_flutter
        pluginClass: SfmcFlutterPlugin
      ios:
        pluginClass: SfmcFlutterPlugin